#!/bin/bash

source /usr/share/yunohost/helpers

#=================================================
# BACKUP THE APP MAIN DIR
#=================================================

ynh_backup "$install_dir"

#=================================================
# BACKUP THE NGINX CONFIGURATION
#=================================================

ynh_backup "/etc/nginx/conf.d/$domain.d/$app.conf"

#=================================================
# END OF SCRIPT
#=================================================

ynh_print_info "Backup script completed for Laverna. (YunoHost will then actually copy those files to the archive)."
